"""Factor research board -- Alpha101 + momentum/volatility factors with research metrics.

Per symbol, from an injected candle client (``client.get_candles(symbol,
granularity, limit)`` returning rows ``[ts, o, h, l, c, v]`` as strings or
numbers): take 350 x 1h and 350 x 1d candles, keep CLOSED bars only
(``_closed_bars``), evaluate the 19 adapted alphas from the
quantdesk/factors/alpha101.py registry plus the momentum/volatility factor
stack (quantdesk/factors/tsmom.py, quant.py), and attach research metrics to
every series:

- Rank-IC:     TIME-SERIES Spearman per symbol, corr(factor_t, ln(P_{t+h}/P_t)),
               reusing quantdesk/backtest/metrics.spearman_rank_ic verbatim. A
               cross-sectional IC over a handful of symbols is degenerate and
               deliberately NOT computed -- the payload says so in ic_convention.
- Decay:       the same IC swept over widening horizons.
- Turnover:    self_corr_lag1 = Spearman(factor_t, factor_{t-1}) -- the
               turnover-proxy column of docs/RESEARCH_DISCIPLINE.md.
- Correlation: pairwise Spearman across 1h-timeframe series ONLY; daily rows
               are excluded because mixing timeframes by bar index is nonsense.

The momentum and volatility rows are series-ified by PREFIX EVALUATION of
the library functions themselves -- fn(closes[:t+1]) for every t
(_prefix_series / _prefix_family) -- so the board series is generated by the
exact function any consumer calls and the two cannot diverge. The alpha rows
are one-pass series; their no-lookahead property is asserted by the
prefix-determinism test instead. The O(n^2) prefix cost is affordable at 350
bars.

HONESTY (docs/RESEARCH_DISCIPLINE.md): at 60-120bps/side retail fees these are research
observables, not signals -- the payload carries a disclaimer, refuses to print
an IC below 30 pairs (n is still reported), flags overlapping-horizon ICs with
n_eff ~ n/h, and contains NO action or recommendation field anywhere.

Failure isolation: a symbol whose fetch fails becomes {"symbol", "ok": False,
"error"}; a factor whose math fails becomes an all-None series and an
ok:false row. Nothing here raises into the caller.

MICROSTRUCTURE (additive): every symbol row also carries a "microstructure"
section -- the seven quantdesk/factors/microstructure.py factors evaluated on
the newest book_top10 snapshots (+ market_trades prints) from the Parquet
lake, built by quantdesk/research/microstructure_lake.py. It is lake-fed and
independent of the candle fetch, so even a fetch-failed symbol row carries
it. Observables only: latest value + window mean/std, NO IC/decay/turnover
(no evaluation history yet -- the section says so), and a first-class
{"available": false} empty state when the lake holds no book data.

No network code lives here: the candle client and the optional funding client
are injected by the caller (see quantdesk/demo for a synthetic one).
"""
from __future__ import annotations

import math
import time
from pathlib import Path
from typing import Any, Callable, Sequence

from ..backtest.metrics import spearman_rank_ic
from ..factors.alpha101 import ALPHAS
from ..factors.tsmom import MIN_BARS_DAILY, tsmom_score
from ..factors.quant import (
    _percentile_rank,
    _rolling_realized_vol,
    _zscore,
    funding_zscore_summary,
    momentum_zscores,
    volatility_regime,
)
from .microstructure_lake import build_micro_section

Series = list  # list[float | None], oldest -> newest (quantdesk/factors/alpha101.py convention)

# Data plane. Hourly-factor constants are the library defaults, so the
# prefix-evaluated series see exactly what a consumer would run.
_CANDLE_LIMIT = 350           # venue cap per request; a032 needs ~295 bars of warmup
_PERIODS_PER_YEAR = 24 * 365  # hourly bars, crypto trades 24/7
_MOM_HORIZONS = [6, 24, 72]   # 6h / 1d / 3d
_MOM_LOOKBACK = 120
_VOL_WINDOW = 24
_VOL_LOOKBACK = 120

_TTL_S = 60      # 1h bars change hourly; a 60s cache is already generous
_SPARK_N = 24    # factor values exposed for the frontend sparkline
_MIN_IC_PAIRS = 30  # below this, report n but refuse to print an IC (honesty gate)
_MIN_IC_EFF = 8     # overlapping horizons: minimum n_eff (= n//h) to print an IC

# IC horizons and decay lags per timeframe family.
_IC_HORIZONS_1H = ((1, "1h"), (24, "24h"))
_IC_HORIZONS_1D = ((1, "1d"),)
_DECAY_LAGS_1H = (1, 2, 3, 4, 6, 12, 24, 48)
_DECAY_LAGS_1D = (1, 2, 3, 5, 7, 10)

# First bar at which each prefix-evaluated library factor can emit a value:
# an h-bar return needs h+1 closes and a z-score needs 2 history samples (h+3);
# a realized-vol estimate needs window+1 closes, its z-score window+3.
_MOM_NEED = {h: h + 3 for h in _MOM_HORIZONS}
_VOL_PCT_NEED = _VOL_WINDOW + 1
_VOL_Z_NEED = _VOL_WINDOW + 3

_DISCLAIMER = {
    "en": (
        "Research observables, not trading signals: at 60-120bps/side retail fees, "
        "formulaic micro-alphas are not standalone-viable. Rank-IC 0.02-0.05 is the "
        "institutional register; materially higher |IC| on small samples is treated "
        "as noise or leakage until proven otherwise."
    ),
    "ref": "docs/RESEARCH_DISCIPLINE.md",
}
_IC_CONVENTION = (
    "time-series Spearman per symbol: corr(factor_t, ln(P_{t+h}/P_t)); "
    "a cross-sectional IC over a handful of symbols is degenerate and deliberately not computed"
)
_FUNDING_NOTE = (
    "8h funding settlements are not index-aligned to 1h bars; "
    "IC deferred until an aligned series exists"
)
_CORR_BASIS = (
    "1h-timeframe factors only (alphas + mom_z + vol rows); daily rows excluded — "
    "mixing timeframes by bar index is nonsense"
)


def _safe(fn: Callable[[], Any], default: Any = None) -> Any:
    try:
        return fn()
    except Exception:  # noqa: BLE001 — one dead factor must not kill the symbol
        return default


# --------------------------------------------------------------------------- #
# data plane
# --------------------------------------------------------------------------- #
def _closed_bars(
    candles: list[list], bar_seconds: float, now: float | None = None
) -> dict[str, list[float]]:
    """CLOSED bars from venue candle rows [ts, o, h, l, c, v] (strings tolerated
    -- venue adapters often return string fields; everything is float-coerced).

    Works for any granularity and keeps the whole OHLCV frame: drops the still-forming last bar (ts + bar_seconds > now — a
    partial bar is intra-bar lookahead and would make the panel flicker) and
    drops unparseable rows instead of raising."""
    now = now if now is not None else time.time()
    out: dict[str, list[float]] = {"ts": [], "o": [], "h": [], "l": [], "c": [], "v": []}
    for row in candles or []:
        try:
            vals = [float(row[i]) for i in range(6)]
        except (TypeError, ValueError, IndexError):
            continue
        if vals[0] + bar_seconds > now:
            continue  # forming bar
        for key, val in zip(("ts", "o", "h", "l", "c", "v"), vals):
            out[key].append(val)
    return out


# --------------------------------------------------------------------------- #
# prefix evaluation — the same-implementation guarantee
# --------------------------------------------------------------------------- #
def _prefix_family(
    xs: Sequence[float],
    fn: Callable[[Sequence[float]], Any],
    min_bars: int,
    extractors: dict[str, Callable[[dict], Any]],
) -> dict[str, Series]:
    """Evaluate a library factor function on every prefix xs[:t+1] and pull
    one aligned series per extractor key — ONE fn call per prefix, shared by
    all extractors. Element t depends only on bars <= t by construction, so the
    result is lookahead-free, and the series is generated by the exact library
    function any consumer calls. Failed calls / missing keys / non-finite values
    -> None."""
    n = len(xs)
    out: dict[str, Series] = {name: [None] * n for name in extractors}
    for t in range(max(min_bars, 1) - 1, n):
        prefix = xs[: t + 1]
        d = _safe(lambda: fn(prefix))
        if not isinstance(d, dict):
            continue
        for name, extract in extractors.items():
            val = _safe(lambda: extract(d))
            if isinstance(val, (int, float)) and math.isfinite(val):
                out[name][t] = float(val)
    return out


def _prefix_series(
    xs: Sequence[float],
    fn: Callable[[Sequence[float]], Any],
    min_bars: int,
    extract: Callable[[dict], Any],
) -> Series:
    """[extract(fn(xs[:t+1])) if t+1 >= min_bars else None, ...] — the
    single-series convenience over _prefix_family."""
    return _prefix_family(xs, fn, min_bars, {"value": extract})["value"]


_VOL_EXTRACTORS = {
    "vol_pct": lambda d: d.get("percentile"),
    "vol_z": lambda d: d.get("zscore"),
}


def _vol_family(closes: Sequence[float]) -> dict[str, Series]:
    """vol_pct / vol_z series, element-for-element EQUAL to the literal prefix
    sweep of quant.volatility_regime (proven exhaustively by
    test_vol_family_matches_prefix_evaluation) at O(n) stdev calls instead of
    O(n * lookback).

    Why not the literal sweep: it recomputes ~lookback+1 rolling-vol windows
    per bar — the profiled hotspot (~2.3s/symbol at 350 bars; statistics.stdev
    is Fraction-exact on floats since 3.12) — yet window k of the full series
    is bit-identical to window k of every prefix that contains it, because
    _rolling_realized_vol is a pure trailing map. So: compute the rolling-vol
    series ONCE, then apply volatility_regime's own outer wiring per bar t
    (current = vols[t-w], history = the previous <=lookback vols, quant's
    _percentile_rank/_zscore, same rounding) — quant's helpers, not a
    reimplementation of the math. Non-positive closes break the index
    correspondence (_rolling_realized_vol skips bad pairs), so a pathological
    feed falls back to the literal prefix sweep (exact by construction;
    cost is irrelevant on junk data)."""
    if any(x is None or x <= 0 for x in closes):
        return _prefix_family(
            closes,
            lambda xs: volatility_regime(xs, _VOL_WINDOW, _VOL_LOOKBACK, _PERIODS_PER_YEAR),
            _VOL_PCT_NEED,
            _VOL_EXTRACTORS,
        )
    n = len(closes)
    out: dict[str, Series] = {"vol_pct": [None] * n, "vol_z": [None] * n}
    vols = _rolling_realized_vol(list(closes), _VOL_WINDOW)
    for k, current in enumerate(vols):
        t = k + _VOL_WINDOW  # bar whose prefix ends at this window
        history = vols[max(0, k - _VOL_LOOKBACK): k]
        pct = _percentile_rank(history, current) if history else 0.5
        z = _zscore(history, current)
        out["vol_pct"][t] = float(round(pct, 3))
        out["vol_z"][t] = float(round(z, 3)) if z is not None else None
    return out


# --------------------------------------------------------------------------- #
# research metrics (all TIME-SERIES; see module docstring for why)
# --------------------------------------------------------------------------- #
def forward_log_returns(closes: Sequence[float], h: int) -> Series:
    """fr[t] = ln(closes[t+h] / closes[t]); None for t >= n-h (future unknown)
    and on non-positive prices (guarded, never an exception)."""
    n = len(closes)
    out: Series = [None] * n
    for t in range(n - h):
        a, b = closes[t], closes[t + h]
        if a is not None and b is not None and a > 0 and b > 0:
            out[t] = math.log(b / a)
    return out


def _pairs(
    xs: Sequence[float | None], ys: Sequence[float | None]
) -> tuple[list[float], list[float]]:
    """Jointly non-None (x, y) pairs, matched by bar index."""
    a: list[float] = []
    b: list[float] = []
    for x, y in zip(xs, ys):
        if x is not None and y is not None:
            a.append(x)
            b.append(y)
    return a, b


def ic_for(series: Series, closes: Sequence[float], h: int) -> dict[str, Any]:
    """Time-series Rank-IC of a factor at horizon h bars.

    ic is None below _MIN_IC_PAIRS pairs or on degenerate ranks — n is reported
    regardless (the honesty gate never hides sample size). h > 1 means
    OVERLAPPING forward windows (consecutive windows share h-1 bars), so the
    row also carries n_eff = n // h as the effective independent sample."""
    xs, ys = _pairs(series, forward_log_returns(closes, h))
    n = len(xs)
    ic = spearman_rank_ic(xs, ys) if n >= _MIN_IC_PAIRS else None
    if ic is not None and h > 1 and (n // h) < _MIN_IC_EFF:
        # Overlapping windows: n pairs but only n//h independent observations.
        # An IC backed by a handful of effective samples is noise dressed up
        # as a number — the honesty gate nulls it (n and n_eff still ship).
        ic = None
    out: dict[str, Any] = {"h": h, "ic": round(ic, 4) if ic is not None else None, "n": n}
    if h > 1:
        out["n_eff"] = n // h
    out["overlap"] = h > 1
    return out


def decay_for(series: Series, closes: Sequence[float], lags: Sequence[int]) -> dict[str, list]:
    """IC decay profile: the ic_for sweep over widening horizons."""
    ics: list[float | None] = []
    ns: list[int] = []
    for h in lags:
        r = ic_for(series, closes, h)
        ics.append(r["ic"])
        ns.append(r["n"])
    return {"lags": list(lags), "ic": ics, "n": ns}


def self_corr_lag1(series: Series) -> float | None:
    """Spearman(factor_t, factor_{t-1}) — the turnover proxy mandated by
    docs/RESEARCH_DISCIPLINE.md: rank persistence near 1 means a slow, cheap-
    to-trade factor; near 0 means the ranking churns every bar."""
    xs, ys = _pairs(series[1:], series[:-1])
    rho = spearman_rank_ic(xs, ys)
    return round(rho, 4) if rho is not None else None


def corr_matrix(series_by_id: dict[str, Series]) -> dict[str, Any]:
    """Pairwise Spearman between factor series on jointly-non-None indices.

    Symmetric with unit diagonal; a cell is None when the overlap is below
    _MIN_IC_PAIRS or a leg is degenerate. Callers must pass series from ONE
    timeframe only — pairing different timeframes by bar index is meaningless."""
    ids = list(series_by_id)
    k = len(ids)
    matrix: list[list[float | None]] = [[None] * k for _ in range(k)]
    for i in range(k):
        matrix[i][i] = 1.0
        for j in range(i + 1, k):
            xs, ys = _pairs(series_by_id[ids[i]], series_by_id[ids[j]])
            cell = None
            if len(xs) >= _MIN_IC_PAIRS:
                rho = spearman_rank_ic(xs, ys)
                cell = round(rho, 4) if rho is not None else None
            matrix[i][j] = matrix[j][i] = cell
    return {"ids": ids, "matrix": matrix}


# --------------------------------------------------------------------------- #
# payload rows
# --------------------------------------------------------------------------- #
def _factor_row(
    meta: dict[str, Any],
    series: Series,
    closes: Sequence[float],
    *,
    timeframe: str,
    horizons: Sequence[tuple[int, str]],
    lags: Sequence[int],
    need: int,
    diag: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """One board row. A factor still inside its warmup (no valid value
    anywhere in the series) reports {ok: False, value: None, need} with
    ic []/decay None — the tsmom_score {ok, n, need} shape — instead of
    pretending to have statistics. A factor with history whose LATEST bar is
    merely degenerate (e.g. a054 on a high==low candle) keeps ok/IC/turnover:
    the history-backed statistics are valid, only value is null this bar."""
    latest = series[-1] if series else None
    n_obs = sum(1 for v in series if v is not None)
    warming_up = n_obs == 0
    row = dict(meta)
    row["timeframe"] = timeframe
    row["ok"] = not warming_up
    row["value"] = round(latest, 4) if latest is not None else None
    row["n_obs"] = n_obs
    if warming_up:
        row["need"] = need
    row["turnover_proxy"] = self_corr_lag1(series)
    if warming_up:
        row["ic"] = []
        row["decay"] = None
    else:
        ics: list[dict[str, Any]] = []
        for h, label in horizons:
            r = ic_for(series, closes, h)
            entry: dict[str, Any] = {"h": r["h"], "label": label, "ic": r["ic"], "n": r["n"]}
            if "n_eff" in r:
                entry["n_eff"] = r["n_eff"]
            entry["overlap"] = r["overlap"]
            ics.append(entry)
        row["ic"] = ics
        row["decay"] = decay_for(series, closes, lags)
    row["spark"] = [None if v is None else round(v, 6) for v in series[-_SPARK_N:]]
    if diag is not None:
        row["diag"] = diag
    return row


def build_symbol_factors(
    symbol: str,
    client: Any,
    *,
    funding_client: Any | None = None,
    now: float | None = None,
    lake_root: str | Path | None = None,
) -> dict[str, Any]:
    """Full factor-research bundle for one symbol. Never raises.

    ``client.get_candles(symbol, granularity, limit)`` must return rows
    ``[ts, o, h, l, c, v]`` (strings or numbers, oldest -> newest); the
    optional ``funding_client.get_funding_rate_history(symbol, page_size)``
    returns newest-first rows carrying a ``fundingRate`` field.

    1h fetch failure kills only this symbol ({ok: False, error}); a 1d fetch
    failure degrades to ok:false tsmom rows (need gate) — the hourly panel
    survives. Every factor is individually failure-isolated.

    The lake-fed microstructure section is attached to EVERY return shape
    (success, fetch_failed, insufficient_candles): it needs no network, so a
    dead venue must not hide what the lake holds on disk."""
    now = now if now is not None else time.time()
    micro = _safe(lambda: build_micro_section(symbol, lake_root, now=now)) or {
        "available": False, "note": "microstructure section failed"}
    try:
        candles_1h = client.get_candles(symbol, "1h", limit=_CANDLE_LIMIT)
    except Exception as exc:  # noqa: BLE001 — a symbol that can't be fetched is reported, not fatal
        return {"symbol": symbol, "ok": False, "error": f"fetch_failed: {exc}",
                "microstructure": micro}
    candles_1d = _safe(lambda: client.get_candles(symbol, "1d", limit=_CANDLE_LIMIT), []) or []

    bars = _closed_bars(candles_1h, 3600.0, now)
    o, h, l, c, v = bars["o"], bars["h"], bars["l"], bars["c"], bars["v"]
    closes_1d = _closed_bars(candles_1d, 86400.0, now)["c"]
    if len(c) < 2:
        return {"symbol": symbol, "ok": False, "error": "insufficient_candles",
                "microstructure": micro}

    # ---- 19 Alpha101 rows, registry order --------------------------------- #
    alpha_rows: list[dict[str, Any]] = []
    series_1h: dict[str, Series] = {}  # feeds the 1h-only correlation matrix
    for entry in ALPHAS:
        series = _safe(lambda fn=entry["fn"]: fn(o, h, l, c, v)) or [None] * len(c)
        series_1h[entry["id"]] = series
        meta = {k: entry[k] for k in ("id", "num", "style", "formula", "adaptation",
                                      "paper_ref", "lookback")}
        alpha_rows.append(_factor_row(
            meta, series, c, timeframe="1h",
            horizons=_IC_HORIZONS_1H, lags=_DECAY_LAGS_1H, need=entry["lookback"]))

    # ---- daily family: ONE tsmom_score prefix loop, all keys per call ----- #
    daily = _prefix_family(
        closes_1d,
        lambda xs: tsmom_score(xs),
        MIN_BARS_DAILY,
        {
            "tsmom_score": lambda d: d.get("score"),
            "tsmom_s22": lambda d: d.get("s22"),
            "tsmom_s65": lambda d: d.get("s65"),
            "tsmom_s261": lambda d: d.get("s261"),
            "tsmom_vol_ratio": lambda d: d.get("vol_ratio"),
        },
    )
    d_last = tsmom_score(closes_1d)  # latest diag carries the vol structure too
    diag: dict[str, Any] = {}
    for key in ("s22", "s65", "s261", "sigma_ann", "sigma_fast", "sigma_slow", "vol_ratio"):
        val = d_last.get(key)
        diag[key] = round(val, 4) if isinstance(val, (int, float)) else None

    existing_rows: list[dict[str, Any]] = []
    src_tsmom = "quantdesk/factors/tsmom.py tsmom_score"
    for rid in ("tsmom_score", "tsmom_s22", "tsmom_s65", "tsmom_s261", "tsmom_vol_ratio"):
        existing_rows.append(_factor_row(
            {"id": rid, "source": src_tsmom}, daily[rid], closes_1d,
            timeframe="1d", horizons=_IC_HORIZONS_1D, lags=_DECAY_LAGS_1D,
            need=MIN_BARS_DAILY, diag=diag if rid == "tsmom_score" else None))

    # ---- hourly family: momentum_zscores / volatility_regime prefixes ----- #
    def _mom_extract(key: str) -> Callable[[dict], Any]:
        return lambda d: ((d.get("horizons") or {}).get(key) or {}).get("zscore")

    mom = _prefix_family(
        c,
        lambda xs: momentum_zscores(xs, _MOM_HORIZONS, _MOM_LOOKBACK),
        min(_MOM_NEED.values()),
        {f"mom_z_{n}b": _mom_extract(f"{n}b") for n in _MOM_HORIZONS},
    )
    vol = _vol_family(c)
    for rid, series, src, need in (
        ("mom_z_6b", mom["mom_z_6b"], "quantdesk/factors/quant.py momentum_zscores", _MOM_NEED[6]),
        ("mom_z_24b", mom["mom_z_24b"], "quantdesk/factors/quant.py momentum_zscores", _MOM_NEED[24]),
        ("mom_z_72b", mom["mom_z_72b"], "quantdesk/factors/quant.py momentum_zscores", _MOM_NEED[72]),
        ("vol_pct", vol["vol_pct"], "quantdesk/factors/quant.py volatility_regime", _VOL_PCT_NEED),
        ("vol_z", vol["vol_z"], "quantdesk/factors/quant.py volatility_regime", _VOL_Z_NEED),
    ):
        series_1h[rid] = series
        existing_rows.append(_factor_row(
            {"id": rid, "source": src}, series, c, timeframe="1h",
            horizons=_IC_HORIZONS_1H, lags=_DECAY_LAGS_1H, need=need))

    # ---- funding: latest value only ---------------------------------------- #
    funding = None
    if funding_client is not None:
        def _funding():
            hist = funding_client.get_funding_rate_history(symbol, page_size=200) or []
            rates = [float(r.get("fundingRate")) for r in hist if r.get("fundingRate") is not None]
            rates.reverse()  # venue returns newest-first; quant expects oldest->newest
            return funding_zscore_summary(rates) if rates else None
        funding = _safe(_funding)
    fz = funding.get("zscore") if funding else None
    existing_rows.append({
        "id": "funding_z",
        "source": "quantdesk/factors/quant.py funding_zscore_summary",
        "timeframe": "8h",
        "ok": fz is not None,
        "value": fz,
        "n_obs": (funding or {}).get("samples") or 0,
        "turnover_proxy": None,
        "ic": None,  # 8h settlement series is not index-aligned to 1h bars
        "decay": None,
        "spark": None,
        "note": _FUNDING_NOTE,
    })

    corr = corr_matrix(series_1h)
    return {
        "symbol": symbol,
        "ok": True,
        "bars_1h": len(c),      # hoisted to the payload top by compute_factors
        "bars_1d": len(closes_1d),
        "alpha101": alpha_rows,
        "existing": existing_rows,
        "microstructure": micro,
        "correlation": {"basis": _CORR_BASIS, "ids": corr["ids"], "matrix": corr["matrix"]},
    }


def compute_factors(
    symbols: list[str],
    client: Any,
    *,
    funding_client: Any | None = None,
    now: float | None = None,
    lake_root: str | Path | None = None,
    with_funding: bool = False,
) -> dict:
    """Build the board payload for every symbol through ONE injected candle
    client (``client.get_candles(symbol, granularity, limit)`` -> rows
    ``[ts, o, h, l, c, v]``). Symbols are evaluated sequentially -- a shared
    client need not be thread-safe -- and per-symbol failures stay isolated.

    Funding rows are attached only when ``with_funding`` is true AND a
    ``funding_client`` is supplied. ``lake_root=None`` means the default lake
    (``$QUANTDESK_LAKE_ROOT`` or ``./data/lake``); tests point it at a temp lake."""
    fc = funding_client if with_funding else None
    rows = [
        build_symbol_factors(sym, client, funding_client=fc, now=now, lake_root=lake_root)
        for sym in symbols
    ]

    bars_1h = bars_1d = 0
    for row in rows:
        bars_1h = max(bars_1h, row.pop("bars_1h", 0))
        bars_1d = max(bars_1d, row.pop("bars_1d", 0))
    return {
        "generated_at": now if now is not None else time.time(),
        "ttl_s": _TTL_S,
        "granularity": "1h",
        "bars_1h": bars_1h,
        "bars_1d": bars_1d,
        "disclaimer": dict(_DISCLAIMER),
        "ic_convention": _IC_CONVENTION,
        "symbols": rows,
    }
